### ISSUE TITLE
JSONLD checker relies on a old version of jsonld

### ISSUE THREAD

**Issue by lemoustachiste** [gjgd/jsonld-checker#91]
Hi,

I am using did-key-js from Transmute in a WIP branch of my project (https://github.com/blockchain-certificates/cert-verifier-js) to expand secp256k1 did:keys (the digital bazaar implementation does not seem to support it).

When trying to run the node build (pre-compiled with rollup), I have an issue that pops up:

```
Cannot find module 'core-js/fn/object/entries'
```
From what I could find online, this is an old path for `core-js@2` which is irrelevant with `core-js@3`.

I have located the dependency path as such: `@did-core/did-ld-json` > `jsonld-checker` > `jsonld@3.1.1`. 
The issue comes from the latter package, if I delete it from the local `jsonld-checker/node_modules` directory (and rely on my own `jsonld` node_module dep - currently 5.2.0 - will look at bumping to 6), I do not get the above error.

I see the latest version of `jsonld-checker` (0.1.8-unstable.4), still relies on `jsonld@3.1.1`.

I can do a workaround in my repo on a post install to delete this dependency, but I would rather go a clean way by cleaning up the dependency chain.

Is this something you think you could address?

**Comment by gjgd** [comment]
Bonjour Julien 👋 

Unfortunately I don't have time to maintain this project anymore, but happy to review and merge PRs if you know how to fix the issue

**Comment by lemoustachiste** [comment]
Sounds good, 

There are 2 ways I can think of:
- fix jsonld dep to a more recent version
- remove jsonld dep and make it a peerDependency to rely on the consumer's version.

The only thing that worries me is that there are no automated tests. I don't mind adding some along with the PR, but I'm not sure I wouldn't break something. Is there a way you know that it wouldn't break things (especially at transmute)?

**Comment by gjgd** [comment]
There are a few tests here: https://github.com/gjgd/jsonld-checker/tree/main/packages/lib/src/test

Can't speak to how it would break things in other repos, but if the fix is a breaking change we can publish a new minor version of the lib so that upstream code doesn't update automatically
